api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path("users/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("users/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("", views.getRoutes),
    path("projects/", views.getProjects),
    path("projects/<str:pk>/", views.getProject),
    path("projects/<str:pk>/vote/", views.projectVote),
]

devsearch/urls.py
from django.contrib import admin
from django.urls import path, include

# images
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("", include("users.urls")),
    path("api/", include("api.urls")),
    # reset password
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="reset_password_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="reset_password_complete.html"
        ),
        name="password_reset_complete",
    ),
]

# images
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.projects, name="projects"),
    path("project/<str:pk>/", views.project, name="project"),
    path("create-project/", views.createProject, name="create-project"),
    path("update-project/<str:pk>/", views.updateProject, name="update-project"),
    path("delete-project/<str:pk>/", views.deleteProject, name="delete-project"),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile


# Create your models here.
class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    feature_image = models.ImageField(null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField("Tag", blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-vote_ratio", "-vote_total", "title"]

    @property
    def reviewers(self):
        queryset = self.review.all().values_list("owner__id", flat=True)
        return queryset

    @property
    def getVoteCount(self):
        reviews = self.review.all()

        upVotes = reviews.filter(value="up").count()
        print("upVotes: ", upVotes)
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ratio = ratio

        self.save()


class Review(models.Model):
    VOTE_TYPE = (
        ("up", "Up Vote"),
        ("down", "Down Vote"),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="review"
    )
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    class Meta:
        unique_together = [["owner", "project"]]

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self):
        return self.name

projects/forms.py
from django.db.models.base import Model
from django.forms import ModelForm, widgets
from django import forms
from .models import Project, Review


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ["title", "feature_image", "description", "demo_link", "source_link"]
        widgets = {
            "tags": forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})

    # self.fields["title"].widget.attrs.update(
    #     {"class": "input", "placeholder": "Add title"}
    # )

    # self.fields["description"].widget.attrs.update(
    #     {"class": "input", "placeholder": "Add title"}
    # )


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ["value", "body"]

    labels = {"value": "Place your vote", "body": "Add a comment with your vote"}

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})

projects/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Project, Tag
from .forms import ProjectForm, ReviewForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from .utils import searchProjects, paginateProjects


# Create your views here.


def projects(request):
    projects, search_query = searchProjects(request)

    custom_range, projects = paginateProjects(request, projects, 6)

    context = {
        "projects": projects,
        "search_query": search_query,
        "custom_range": custom_range,
    }
    return render(request, "projects/projects.html", context)


def project(request, pk):
    projectObj = Project.objects.get(id=pk)
    form = ReviewForm()
    tags = projectObj.tags.all()

    if request.method == "POST":
        form = ReviewForm(request.POST)
        review = form.save(commit=False)
        review.project = projectObj
        review.owner = request.user.profile
        review.save()

        projectObj.getVoteCount

        # update project votecount
        messages.success(request, "Your review was successfully submitted!")
        return redirect("project", pk=projectObj.id)

    return render(
        request,
        "projects/single-project.html",
        {"project": projectObj, "tags": tags, "form": form},
    )


@login_required(login_url="login")
def createProject(request):
    profile = request.user.profile
    form = ProjectForm()

    if request.method == "POST":
        newtags = request.POST.get("newtags").replace(",", " ").split()
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = profile
            project.save()
            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)
            return redirect("account")

    context = {"form": form}
    return render(request, "projects/project_form.html", context)


@login_required(login_url="login")
def updateProject(request, pk):
    # garante que atualize somente os seus respectivos projetos
    profile = request.user.profile
    project = profile.project_set.get(id=pk)

    form = ProjectForm(instance=project)

    if request.method == "POST":
        newtags = request.POST.get("newtags").replace(",", " ").split()

        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            project = form.save()
            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)

            return redirect("account")

    context = {"form": form}
    return render(request, "projects/project_form.html", context)


@login_required(login_url="login")
def deleteProject(request, pk):
    # garante que delete somente os seus respectivos projetos
    profile = request.user.profile
    project = profile.project_set.get(id=pk)

    # form = ProjectForm(instance=project)

    if request.method == "POST":
        project.delete()
        return redirect("account")

    context = {"object": project}
    return render(request, "delete_template.html", context)

projects/templates/projects/project_form.html
{% extends "main.html" %}
{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account'%}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- Input:Text -->
                {% for field in form %}
                <div class="form__field">
                    <label for="formInput#text">{{field.label}}</label>
                    {{field}}
                </div>
               {% endfor %}

               <div class="form__field">
                {% for tag in project.tags.all %}
                <div class="project-tag tag tag--pill tag--main" data-tag="{{tag.id}}"
                    data-project="{{project.id}}">{{tag.name}} &#215;</div>
                {% endfor %}
                </div>

               <div class="form__field">
                <label for="formInput#text">Tags</label>
                <textarea class="input" name="newtags" placeholder="add tags here...">  </textarea>
               </div>





                
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>






{% endblock content %}

projects/templates/projects/projects.html
{% extends 'main.html' %}

{% block content %}


<!-- Main Section -->
<main class="projects">
   <section class="hero-section text-center">
     <div class="container container--narrow">
       <div class="hero-section__box">
         <h2>Search for <span>Projects</span></h2>
       </div>

       <div class="hero-section__search">
         <form  id="searchForm" class="form" action="{% url 'projects' %}" method="get">
           <div class="form__field">
             <label for="formInput#search">Search By Projects </label>
             <input class="input input--text" id="formInput#search" type="text" name="search_query" value="{{search_query}}"
               placeholder="Search by Project Title" />
           </div>

           <input class="btn btn--sub btn--lg" type="submit" value="Search" />
         </form>
       </div>
     </div>
   </section>
   <!-- Search Result: DevList -->
   <section class="projectsList">
     <div class="container">
       <div class="grid grid--three">

         {% for project in projects %}
         <div class="column">
           <div class="card project">
             <a href="{% url 'project' project.id %}" class="project">
               <img class="project__thumbnail" src="{{project.feature_image.url}}" alt="project thumbnail" />
               <div class="card__body">
                 <h3 class="project__title">{{project.title}}</h3>
                 <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">By {{project.owner.name}}</a></p>
                 <p class="project--rating">
                   <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Posititive
                   Feedback ({{project.vote_total}}) Vote{{project.vote_total|pluralize:"s"}}
                 </p>
                 <div class="project__tags">

                  {% for tag in project.tags.all  %}

                   <span class="tag tag--pill tag--main">
                     <small>{{tag}}</small>
                   </span>

                   {% endfor %}
                 </div>
               </div>
             </a>
           </div>
         </div>
         {% endfor %}
        

        

       </div>
     </div>
   </section>

   {% include 'pagination.html' with queryset=projects custom_range=custom_range %}

 
 </main>








{% endblock content%}

projects/templates/projects/single-project.html
{% extends 'main.html' %}

{% block content %}


  <main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <h3 class="singleProject__subtitle">Tools & Stacks</h3>
          <div class="singleProject__toolStack">

            {% for tag in project.tags.all  %}
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{tag}}</small>
            </span>
            {% endfor %}

          </div>

          {% if project.source_link %}
          <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>Source Code
          </a>
          {% endif %}

          {% if project.demo_link %}
          <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>Live demo
          </a>
          {% endif %}

        </div>
        <div class="column column--2of3">
          <img class="singleProject__preview" src="{{project.feature_image.url}}" alt="portfolio thumbnail" />
          <a href="profile.html" class="singleProject__developer">{{project.owner.name}}</a>
          <h2 class="singleProject__title">{{project.title}}</h2>
          <h3 class="singleProject__subtitle">About the Project</h3>
          <div class="singleProject__info">{{project.description}}</div>

          <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>
            <h5 class="project--rating">
              {{project.vote_ratio}}% Positive Feedback ({{project.vote_total}}
              Vote{{project.vote_total|pluralize:"s"}})
            </h5>

            {% if request.user.profile.id in project.reviewers  %}
              <p> You have already submitted your review for this project</p>
            {% elif request.user.profile == project.owner %}
              <p> you cannot review your own work </p>
            
            {% elif request.user.is_authenticated %}
            <form class="form" action="{% url 'project' project.id %}" method="POST">
              {% csrf_token %}
              {% for field in form %}
              <div class="form__field">
                <label for="formInput#textarea">{{field.label}}</label>
                 {{field}}
              </div>
              {% endfor %}
              <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
            </form>
            {% else %}
             <a href="{% url 'login' %}?next={{request.path}}">Please login to leave a review</a>
            {% endif %}
          
            <div class="commentList">
              {% for review in project.review_set.all %}
              {% if review.body %}
              <div class="comment">
                <a href="profile.html">
                  <img class="avatar avatar--md"
                    src="{{review.owner.profile_image.url}}" alt="user" />
                </a>

                
                <div class="comment__details">
                  <a href="" class="comment__author">{{review.owner.name}}</a>
                  <p class="comment__info">
                   {{review.body|linebreaksbr}}
                  </p>
                </div>
              
              </div> 
              {% endif %}
              {% endfor %}
            </div>
           


          </div>
        </div>
      </div>
    </div>
    </div>
  </main>




  {% endblock content %}